### ISSUE TITLE
Nico's fancy writing style is not recognized by some versions of the intel compiler 

### ISSUE THREAD

**Issue by segmentat10nfault** [MALBECC/lio#67] opened 2016-12-27 01:22 UTC
I suggest to add an ifdef FANCY_NICO (actually, that is not a bad name for the github group.. ;P)

**Comment by Nick-Chaos** [comment] 2016-12-27 11:30
i need more details, which is the problem?, compiler version?
bash is set in ascii?

**Comment by ramirezfranciscof** [comment] 2016-12-27 14:18
Do you mean that the output writes giberish instead of the expected symbols? The same happened to me in some computers; but we fixed it by changing some configurations related to the language of the system or something like that.

Even so, most of us agree that we have to have a default format that is less stylish and more plain.

**Comment by segmentat10nfault** [comment] 2016-12-27 14:18
The problem is that it doesn't recognize the special caracters of the
frames.

compiler version = intel 2013.

I don't know what you mean about bash being set in ascii.

**Comment by segmentat10nfault** [comment] 2016-12-27 14:22
No, I mean it does not even compile

**Comment by segmentat10nfault** [comment] 2016-12-27 14:24
A plain format is better even for performance reasons.. I don't know which
is exactly the impact, but it sure increases de i/o a lot!

**Comment by ramirezfranciscof** [comment] 2016-12-27 14:44
Looking at the error log from @segmentat10nfault computer I found the following complaint (repeated for several lines):

> extras.f90(33): error #5145: Invalid blank/tab
>       ════════════════════════════════════╗")
> ------^

It would seem that a closing set of double commas is needed, the compiler is interpreting the continuation symbol as part of the output text. Compare usage in line 132 vs lines 279.

---

Then there is another one but after a "vim extras.f90", so perhaps this one is because of some modification @segmentat10nfault made on the code. I would concentrate on the other one, but just for reference I will leave it here:

>  extras.f90(138): error #6785: This name does not match the unit name.
>  [LIO_LOGO2]
>         end subroutine LIO_LOGO2
> -----------------------^

**Comment by segmentat10nfault** [comment] 2016-12-27 14:49
Thanks @ramirezfranciscof.. Actually the seccond error is my bad so lets
forget about that an focus on the first one.

**Comment by ramirezfranciscof** [comment] 2016-12-27 14:53
I would have thought so.

Issue assigned to @Nick-Chaos . If you can't reproduce the error before doing the modifications, please check with @segmentat10nfault again after committing the fix and once given confirmation, close the issue.

**Comment by Nick-Chaos** [comment] 2016-12-27 16:51
i cant check it at this moment. had u modified extras.f90 file??
that is a common error that appear if exced number of characters per line.
have you got same problem with commit 6fc10484903acbaec4f41654f19d927a75578ea5 of rc? (last tested by me)

**Comment by segmentat10nfault** [comment] 2016-12-27 16:59
I modified every ¨write¨ in the code to avoid using that writing scheme
(don´t worry I wont merge it).. I will try with the commit you are
mentioning, but I believe the problem is related to the recognition of the
characters. (BTW: Can someone explain me why are we speaking in english?)

**Comment by Nick-Chaos** [comment] 2016-12-27 17:09
Probably you exceeded max number of characters in line 32-33. 

i can check it on thursday morning at university. (yes, MORNING)

We speak in english for support Trump. Of course nano idea

**Comment by ramirezfranciscof** [comment] 2017-01-19 12:12
@segmentat10nfault @Nick-Chaos  has this been solved??

**Comment by segmentat10nfault** [comment] 2017-01-19 12:27
No, I have yo work on that..

**Comment by fedepedron** [comment] 2017-06-12 17:58
Fixed in #100

**Closed by fedepedron** 2017-06-12 17:58 UTC
