### ISSUE TITLE
Stop using libcuda.so

### ISSUE THREAD

**Issue by ramirezfranciscof** [MALBECC/lio#53] opened 2015-08-25 19:38 UTC
I am opening this as a request from @segmentat10nfault , I don't really know much about this subject.

Apparently, LIO is currently using the library libcuda.so, which is from the drivers of the video card. This implies a series of problems such as not being able to install the program in clusters. It should be only using libraries from the cuda toolkit instead. Do we know whose code needs this library and if he/she can find an alternative library?

**Comment by chopkins906** [comment] 2015-08-25 20:17
I think it's been a dependency pretty much since the beginning, so I assume it was needed (at least at some point) by the XC code.  Not sure if that's still true...

I'm kind of surprised that the libcuda dependency is causing problems installing on clusters.  I've installed lio on several clusters, and libcuda was provided somewhere (it might require some digging through non-standard directories to find it though).

**Comment by segmentat10nfault** [comment] 2015-08-25 20:23
the problem is that those drivers are not usually installed in the frontend
of a cluster.. in those cases you can log into a node and compile the
code... i gess that not every sysadmin will allow you to do that..

**Comment by chopkins906** [comment] 2015-08-25 21:09
Maybe I've been lucky with my clusters then :) libcuda was always available to link with from the frontend/submit server.  It's not always in a standard directory, or included with the system cuda module, in which case I had to find it in the cluster directory system and manually edit a Makefile or a library environment variable when compiling.  (maybe that's a good enough reason to get rid of it anyway)

libcuda is necessary for using the "CUDA Driver API":  http://docs.nvidia.com/cuda/cuda-driver-api/index.html#axzz3jrXRNJsN

These are usually calls that look like "cuXXX" (rather than "cudaXXX").  A quick search in the code, I see one such call in g2g/init.cpp to cuInit.

Now, I don't know enough about CUDA to know if that call is necessary or can be replaced (I was under the impression that there's an automatic driver initialization at the first call to a "cudaXXX" function, but I could be wrong).  I don't know why @manuelF (or whoever wrote that) chose that call, and I don't know if there's more low-level driver API calls in the XC code.  Those would be the parts of the code that need to be replaced to get rid of libcuda, though.

**Comment by nanolebrero** [comment] 2015-08-25 21:10
In a cluster with GPU the libcuda should be in frontend node for compiling,
even if the frontend heven't GPU.

**Comment by segmentat10nfault** [comment] 2015-08-25 21:20
only if the frontend has nvidia drivers. I rised this issue because i had
exactly this problem.

**Comment by fedepedron** [comment] 2016-12-22 20:47
Will this be solved in the new release, or should it stay as a separate issue?

**Comment by ramirezfranciscof** [comment] 2016-12-22 21:55
@nanolebrero

**Comment by ramirezfranciscof** [comment] 2017-05-05 22:11
Issue has reborn due to our new cluster configuration.

I think we can just include the path during compilation; from what I understand from the [release notes of cuda 6.5](http://developer.download.nvidia.com/compute/cuda/6_5/rel/docs/CUDA_Toolkit_Release_Notes.pdf), they are there for that reason and there should be no problem if these libs are linked instead of the driver ones.

**Comment by fedepedron** [comment] 2017-09-12 14:20
Referenced in #113, closing.

**Closed by fedepedron** 2017-09-12 14:20 UTC
